const alumniData = {
  "2025-2026": [
    {
      name: "DORAIN VERMA",
      designation: "Team Captain",
      image: "assets/alumini/yr25-26/dorain_captain.avif",
      linkedin: "https://www.linkedin.com/in/dorain-verma",
      email: "dorainverma@gmail.com ",
    },
    {
      name: "ANSH TYAGI",
      designation: "Vice Captain",
      image: "assets/alumini/yr25-26/ansh_vc.avif",
      linkedin: "https://www.linkedin.com/in/anshlfg/",
      email: "anshtyagi024@gmail.com",
    },
    {
      name: "ADITYA PATNI",
      designation: "Team Manager",
      image: "assets/alumini/yr25-26/aditya_manager.avif",
      linkedin: "https://www.linkedin.com/in/aditya-patni0905/",
      email: "adityapatni0905@gmail.com",
    },
    {
      name: "KAMAL SHEHARA",
      designation: "Propulsion and Vehicle Dynamics Head",
      image: "assets/alumini/yr25-26/kamal_pnd.avif",
      linkedin: "https://www.linkedin.com/in/kamal-shehara/",
      email: "",
    },
    {
      name: "KUSHANK AGGRAWAL",
      designation: "Aerodynamics Head",
      image: "assets/alumini/yr25-26/kushank_aero.avif",
      linkedin: "https://linkedin.com/in/kushaggar",
      email: "kushank2005@gmail.com",
    },
    {
      name: "ASHUTOSH MISHRA",
      designation: "Treasurer, Electrical & Embedded Head",
      image: "assets/alumini/yr25-26/ashutosh_treas_elec.avif",
      linkedin: "https://www.linkedin.com/in/ashutosh-mishra-3843953ab/",
      email: "",
    },
    {
      name: "MAYUR DAGAR",
      designation: "Steering System Head",
      image: "assets/alumini/yr25-26/mayur_steering.avif",
      linkedin: "https://www.linkedin.com/in/mayur-dagar-1a3015289/",
      email: "mayurdagar9210@gmail.com",
    },
    {
      name: "ABHISHEK GUPTA",
      designation: "Brake System Head",
      image: "assets/alumini/yr25-26/abhishek_brakes.avif",
      linkedin: "https://www.linkedin.com/in/abhishek-gupta-216811269",
      email: "abhi2429@gmail.com",
    },
  ],

  "2024-2025": [],

  "2023-2024": [
    {
      name: "UTKARSH SINGH",
      designation: "Captain",
      image: "assets/alumini/yr23-24/Utkarsh_captain.avif",
      linkedin: "https://www.linkedin.com/in/utkarshsinghxandrew/",
    },
    {
      name: "TANISHQ RASTOGI",
      designation: "Vice Captain",
      image: "assets/alumini/yr23-24/tanishq_vcaptain.avif",
      linkedin: "https://www.linkedin.com/in/tanrastogi2003/",
    },
    {
      name: "SUBHRAJIT ROY",
      designation: "Team Manager",
      image: "assets/alumini/yr23-24/Subhrajit_manager.avif",
      linkedin: "https://www.linkedin.com/in/subhrajit-roy/",
    },
    {
      name: "RISHAB DANDRIYAL",
      designation: "Team Manager (E-SMV)",
      image: "assets/alumini/yr23-24/rishabh_manager.esmv.avif",
      linkedin: "https://www.linkedin.com/in/rishab-dandriyal-45160122a/",
    },
    {
      name: "RISHIT SAINI",
      designation: "Treasurer",
      image: "assets/alumini/yr23-24/rishit_tresurer.avif",
      linkedin: "https://www.linkedin.com/in/rishit-saini-8230bb230/",
    },
    {
      name: "ARJUN ANAND",
      designation: "Steering & Brakes Head",
      image: "assets/alumini/yr23-24/arjun_snb.avif",
      linkedin: "https://www.linkedin.com/in/arjun-anand15/",
    },
    {
      name: "OJAS VINAYAK",
      designation: "Aerodynamics Head",
      image: "assets/alumini/yr23-24/ojas_aero.avif",
      linkedin: "https://www.linkedin.com/in/ojas-vinayak-330895230/",
    },
    {
      name: "UTKARSH SINGH",
      designation: "Aerodynamics Head",
      image: "assets/alumini/yr23-24/utkarsh_aero.avif",
      linkedin: "https://www.linkedin.com/in/utkarsh-singh-0469b2230/",
    },
    {
      name: "JAYANT RAO",
      designation: "Engine & Transmission Head",
      image: "assets/alumini/yr23-24/jayant_EnT.avif",
      linkedin: "https://www.linkedin.com/in/jayant-rao-b92127230/",
    },
    {
      name: "MD. ASHIQUE YUNUS",
      designation: "Electronics & Embedded Systems Head",
      image: "assets/alumini/yr23-24/Ashique_electrical.avif",
      linkedin: "https://www.linkedin.com/in/mdashiqueyunus/",
    },
  ],

  "2022-2023": [
    {
      name: "PARTH SINGH",
      designation: "Ex-Team Captain",
      image: "assets/alumini/yr22-23/parth_captain.avif",
      linkedin: "https://www.linkedin.com/in/parth-singh5/",
    },
    {
      name: "DHRUV BIHANI",
      designation: "Ex-Vice Captain",
      image: "assets/alumini/yr22-23/dhruv_vcaptain.avif",
      linkedin: "https://www.linkedin.com/in/dhruvbihani/",
    },
    {
      name: "HARSHIT GUPTA",
      designation: "Ex-Treasurer",
      image: "assets/alumini/yr22-23/harshit_tresurer.avif",
      linkedin: "https://www.linkedin.com/in/harshitgupta160502/",
    },
    {
      name: "ARYAMAN RAO",
      designation: "Ex-Team Manager(E-SMV)",
      image: "assets/alumini/yr22-23/aryaman_manager(esmv).avif",
      linkedin: "https://www.linkedin.com/in/aryamanrao26/",
    },
    {
      name: "SANSKAR VERMA",
      designation: "Ex-Engine & Transmission Head",
      image: "assets/alumini/yr22-23/sanskar_ent.avif",
      linkedin: "https://www.linkedin.com/in/sanskarverma11072001/",
    },
    {
      name: "MADHAV SACHDEVA",
      designation: "Ex-Steering & Brakes Head",
      image: "assets/alumini/yr22-23/madhav_snb.avif",
      linkedin: "https://www.linkedin.com/in/madhavsachdeva01/",
    },
    {
      name: "ARYAN MITTAL",
      designation: "Ex-Corporate Head",
      image: "assets/alumini/yr22-23/aryan_corpo.avif",
      linkedin: "https://www.linkedin.com/in/aryan-mittal29/",
    },
    {
      name: "ISHAAN SACHAR",
      designation: "Ex-Electronics & Embedded Systems",
      image: "assets/alumini/yr22-23/ishaan_electrical.avif",
      linkedin: "https://www.linkedin.com/in/ishaansachar/",
    },
    {
      name: "PARAS SINGH",
      designation: "Ex-Aerodynamics Head",
      image: "assets/alumini/yr22-23/paras_aero.avif",
      linkedin: "https://www.linkedin.com/in/paras2802/",
    },
    {
      name: "ANUBHAV DHYANI",
      designation: "Ex-Aerodynamics(E-SMV) Head",
      image: "assets/alumini/yr22-23/anubhav_aero(esmv).avif",
      linkedin: "https://www.linkedin.com/in/anubhavdhyani/",
    },
  ],

  "2021-2022": [
    {
      name: "BHASKAR DAS",
      designation: "Team Captain",
      image: "assets/alumini/yr21-22/bhaskar_captain.avif",
      linkedin: "https://www.linkedin.com/in/bhaskardas20/",
    },
    {
      name: "ADITYA CHAUHAN",
      designation: "Vice-Captain",
      image: "assets/alumini/yr21-22/aditya_vcaptain.avif",
      linkedin: "https://www.linkedin.com/in/aditya-chauhan-5b0a14190/",
    },
    {
      name: "VISHESH CHHABRA",
      designation: "Treasurer",
      image: "assets/alumini/yr21-22/vishesh_tresurer.avif",
      linkedin: "https://www.linkedin.com/in/vishesh-chhabra-866aa41b4/",
    },
    {
      name: "PRATHMESH SHARMA",
      designation: "Team Manager (E-SMV)",
      image: "assets/alumini/yr21-22/prathmesh_manager(esmv).avif",
      linkedin: "https://www.linkedin.com/in/prathmesh-sharma-866a64231/",
    },
    {
      name: "AYUSH BHATNAGAR",
      designation: "Team Manager & Engine and Transmission Head",
      image: "assets/alumini/yr21-22/ayush_manager.ent.avif",
      linkedin: "https://www.linkedin.com/in/ayush-bhatnagar-ba2b14193/",
    },
    {
      name: "MANAS SISODIA",
      designation: "Steering Head",
      image: "assets/alumini/yr21-22/manas_steer.avif",
      linkedin: "https://www.linkedin.com/in/manas-sisodia-4ab8a5190/",
    },
    {
      name: "SANCHIT BEHAL",
      designation: "Brakes Head",
      image: "assets/alumini/yr21-22/sanchit_brakes.avif",
      linkedin: "https://www.linkedin.com/in/sanchit-behal-007676196/",
    },
    {
      name: "ISHITA AGRAWAL",
      designation: "Electronics and Embedded Systems Head",
      image: "assets/alumini/yr21-22/ishita_electrical.avif",
      linkedin: "https://www.linkedin.com/in/ishita-agrawal-333650193/",
    },
    {
      name: "SHOBHIN BANSAL",
      designation: "Aerodynamics Head",
      image: "assets/alumini/yr21-22/shobhin_aero.avif",
      linkedin: "https://www.linkedin.com/in/shobhin-bansal-a902161a4/",
    },
    {
      name: "DEVDOOT CHATTERJEE",
      designation: "Aerodynamics (E-SMV) Head",
      image: "assets/alumini/yr21-22/devdoot_aero(esmv).avif",
      linkedin: "https://www.linkedin.com/in/devdoot-chatterjee-7513101b7/",
    },
  ],

  "2020-2021": [
    {
      name: "VIKAS",
      designation: "Team Captain, Engine & Transmission Head",
      image: "assets/alumini/yr20-21/vikas_captain.avif",
      linkedin: "https://www.linkedin.com/in/vikasdtu/",
    },
    {
      name: "MAYANK DAWAR",
      designation: "Team Manager",
      image: "assets/alumini/yr20-21/mayank_vcaptain.avif",
      linkedin: "https://www.linkedin.com/in/mayank-dawar-646a70182/",
    },
    {
      name: "AYUSH SINGH",
      designation: "Team Manager (E-SMV)",
      image: "assets/alumini/yr20-21/ayush_manager.avif",
      linkedin: "https://www.linkedin.com/in/-ayushsingh/",
    },
    {
      name: "ANSHU BIJARNIA",
      designation: "Treasurer",
      image: "assets/alumini/yr20-21/anshu_tresurer.avif",
      linkedin: "https://www.linkedin.com/in/anshu-bijarnia-a346a018b/",
    },
    {
      name: "JAYANT KUMAR",
      designation: "Steering & Brakes Head",
      image: "assets/alumini/yr20-21/jayant_snb.avif",
      linkedin: "https://www.linkedin.com/in/jayant1408/",
    },
    {
      name: "TUSHAR AGGARWAL",
      designation: "Electronics & Embedded Systems Head",
      image: "assets/alumini/yr20-21/tushar_electrical.avif",
      linkedin: "",
    },
    {
      name: "GAURAV AHUJA",
      designation: "Body & Chassis Head",
      image: "assets/alumini/yr20-21/gaurav_aero.avif",
      linkedin: "https://www.linkedin.com/in/gaurav-ahuja1/",
    },
  ],
};